### ISSUE TITLE
Test labels = training labels?

### ISSUE THREAD

**Issue by aronasefaw** [wichtounet/cifar-10#1]
Line 292 in the code: `read_test(test_limit, dataset.training_images, dataset.training_labels, [] { return Image(3, 32, 32); });`
should be : `read_test(test_limit, dataset.test_images, dataset.test_labels, [] { return torch::empty({3, 32, 32}, torch::kUInt8); });`

**Comment by wichtounet** [comment]
You are absolutely right. Thanks for mentioning it, it's fixed 👍
